[build]
  publish = "."
  functions = "functions"
  command = "npm install"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/api/reports"
  to = "/.netlify/functions/reports"
  status = 200

[[redirects]]
  from = "/api/reports/*"
  to = "/.netlify/functions/reports/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200